"""
task_types.py: Core type definitions for Agentic RAG v2 (ExecutionGraph).

Defines the task taxonomy and the ExecutionGraph that drives ALL downstream
modules via a topologically-sorted directed graph of workflow nodes.

Architecture v2:
    TaskAnalyzer → TaskAnalysis → StrategyPlanner → ExecutionGraph
                                                          |
                +------------------------------------------+------------------+
                |          |          |           |             |             |
          RetrieveNode  OrganizeNode  DecideNode  MergeNode  ReasonNode  VerifyNode
                |          |          |           |             |             |
                +------------------------------------------+------------------+
                                                          |
                                                      DeepSeek
                                                         |
                                                      Answer

Key Design (v2):
    - ExecutionGraph replaces flat ExecutionPlan
    - Each node is typed: "retrieve" | "organize" | "reason" | "decide" | "merge" | "verify"
    - Nodes form a directed graph with next[] and branches{}
    - Pipeline = GraphExecutor that topologically walks the graph
    - Supports: sequential, parallel branches, conditional branching, multi-hop retrieval
    - Each adaptive component is independently measurable for ablation
"""

from dataclasses import dataclass, field
from typing import List, Dict, Optional, Any
from enum import Enum


class TaskType(str, Enum):
    """
    Industry-domain reasoning task types.

    These are NOT question formats (QA / FillBlank / MultipleChoice).
    They describe the reasoning task required to answer the question.
    """
    COMPARISON = "comparison"
    DIAGNOSIS = "diagnosis"
    SELECTION = "selection"
    CALCULATION = "calculation"
    STANDARD_INTERPRETATION = "standard_interpretation"
    PROCEDURE = "procedure"
    EXPLANATION = "explanation"
    GENERAL = "general"


# ============================================================
# Question Format (题型) — 独立于 TaskType 的"题目形式"维度
# ============================================================
# 数据集 CSV `_format` 列即"题型"真值标签（非 TaskType 推理任务类型）。
# 方案B：TaskAnalysis 新增 `format` 字段存 `_format` 真值(归一化)作为"题型"，
#   保留 task(8类推理任务) 不变。IndustryBench 该列仅 4 个取值。

QUESTION_FORMATS = ["QA", "FillBlank", "MultipleChoice", "Calculation"]

# 中文 `_format` 标签 → 英文题型枚举
CN2EN_FORMAT = {
    "问答题": "QA",
    "填空题": "FillBlank",
    "选择题": "MultipleChoice",
    "计算题": "Calculation",
    "问答": "QA",
    "填空": "FillBlank",
    "选择": "MultipleChoice",
    "计算": "Calculation",
}


def infer_format_heuristic(question: str) -> str:
    """
    No-`_format` fallback: heuristically pick a standard 题型.
    Returns one of QUESTION_FORMATS.
    """
    q = (question or "").strip()
    if any(b in q for b in ["___", "____", "＿", "___?"]):
        return "FillBlank"
    head = q[:20]
    if any(tok in head for tok in ["A.", "A、", "A)", "A．", "B.", "B、", "C.", "C、", "D."]):
        return "MultipleChoice"
    if any(kw in head for kw in ["计算", "多少", "数值", "为多少", "多大", "电压", "电流",
                                  "功率", "mm", "kW", "Hz", "kg", "℃"]):
        return "Calculation"
    return "QA"


def normalize_format(q_fmt, question: str = "") -> str:
    """
    Normalize any incoming 题型 value (Chinese label / English enum / empty)
    to one of QUESTION_FORMATS. Falls back to infer_format_heuristic(question).
    """
    if q_fmt is None:
        q_fmt = ""
    s = str(q_fmt).strip()
    if s in QUESTION_FORMATS:
        return s
    if s in CN2EN_FORMAT:
        return CN2EN_FORMAT[s]
    lowered = s.lower().replace("_", "").replace(" ", "")
    alias = {
        "qa": "QA", "fillblank": "FillBlank", "blank": "FillBlank",
        "multiplechoice": "MultipleChoice", "choice": "MultipleChoice",
        "selection": "MultipleChoice", "calculation": "Calculation",
        "calc": "Calculation", "math": "Calculation",
    }
    if lowered in alias:
        return alias[lowered]
    # 无法识别或为空 → 启发式兜底
    return infer_format_heuristic(question)


# ============================================================
# Task Analysis Output (Rich Semantic Description)
# ============================================================

@dataclass
class TaskAnalysis:
    """
    Output of TaskAnalyzer - a rich semantic description.

    REDESIGNED: Instead of only returning a task label, this now carries
    a comprehensive semantic description that directly influences all
    downstream modules.

    These fields are GENERATED by the LLM, not hardcoded.

    Attributes:
        task: The classified task type
        confidence: Confidence score (0.0 - 1.0)
        reasoning: Brief reasoning for the classification
        reasoning_complexity: "low", "medium", or "high"
        requires_multi_source: Whether the answer needs multiple evidence sources
        requires_formula: Whether formulas/calculations are needed
        requires_step_reasoning: Whether step-by-step reasoning is needed
        preferred_source: Preferred knowledge source type
        expected_evidence: What type of evidence is expected
        original_question: The original question
        format: The question format / 题型 ("QA", "FillBlank", "MultipleChoice",
                "Calculation"); normalized from the dataset `_format` truth value.
    """
    task: TaskType = TaskType.GENERAL
    confidence: float = 0.0
    reasoning: str = ""
    format: str = ""  # 题型 (题目形式) — 存 CSV `_format` 真值归一化后的标准枚举
    # Rich semantic fields
    reasoning_complexity: str = "medium"  # "low", "medium", "high"
    requires_multi_source: bool = True
    requires_formula: bool = False
    requires_step_reasoning: bool = False
    preferred_source: str = "standard"  # "standard", "manual", "specification", "general"
    expected_evidence: str = "general"  # "comparison", "symptom", "specification", "formula", "procedure", "general"
    original_question: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            "task": self.task.value,
            "confidence": round(self.confidence, 4),
            "reasoning": self.reasoning,
            "format": self.format,
            "reasoning_complexity": self.reasoning_complexity,
            "requires_multi_source": self.requires_multi_source,
            "requires_formula": self.requires_formula,
            "requires_step_reasoning": self.requires_step_reasoning,
            "preferred_source": self.preferred_source,
            "expected_evidence": self.expected_evidence,
            "original_question": self.original_question[:100] if self.original_question else "",
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any], question: str = "") -> "TaskAnalysis":
        """Create from dict (with fallbacks for missing fields)."""
        task_str = data.get("task", "general")
        try:
            task = TaskType(task_str)
        except ValueError:
            task = TaskType.GENERAL

        return cls(
            task=task,
            confidence=float(data.get("confidence", 0.0)),
            reasoning=str(data.get("reasoning", "")),
            reasoning_complexity=str(data.get("reasoning_complexity", "medium")),
            requires_multi_source=bool(data.get("requires_multi_source", True)),
            requires_formula=bool(data.get("requires_formula", False)),
            requires_step_reasoning=bool(data.get("requires_step_reasoning", False)),
            preferred_source=str(data.get("preferred_source", "standard")),
            expected_evidence=str(data.get("expected_evidence", "general")),
            original_question=question,
            format=normalize_format(data.get("format", ""), question),
        )


# ============================================================
# ExecutionGraph (Output of StrategyPlanner v2) — TRULY A WORKFLOW
# ============================================================

GRAPH_NODE_TYPES = {
    "retrieve",   # Retrieve evidence from knowledge base
    "organize",   # Organize/group evidence
    "reason",     # Reasoning step (LLM call)
    "decide",     # Conditional decision (branch)
    "merge",      # Merge multiple evidence streams
    "verify",     # Verify/validate answer
    "end",        # Terminal node
}

GRAPH_NODE_TYPES_LIST = sorted(GRAPH_NODE_TYPES)


@dataclass
class GraphNode:
    """
    A single node in the ExecutionGraph workflow.

    Each node is typed and carries its own params. Nodes are connected
    via `next` (sequential successors) and `branches` (conditional).

    Node Types:
        retrieve  → Execute retrieval operation
        organize  → Organize/group evidence
        reason    → Execute reasoning step (LLM call)
        decide    → Conditional branch based on a condition
        merge     → Merge multiple evidence streams into one
        verify    → Verify/validate step with pass/fail branches
        end       → Terminal node (graph execution ends here)

    Attributes:
        id: Unique node identifier (e.g., "retrieve_1", "decide_sufficient")
        type: Node type from GRAPH_NODE_TYPES
        action: Specific action for this node
        params: Parameters for this node's action
        next: List of successor node IDs (sequential flow)
        branches: Conditional branches {condition: node_id}
                  e.g., {"sufficient": "reason_1", "insufficient": "retrieve_2"}
        fallback: Fallback node ID if primary path fails
        description: Human-readable description of this node's purpose
    """
    id: str
    type: str                           # "retrieve" | "organize" | "reason" | "decide" | "merge" | "verify" | "end"
    action: str = ""                    # e.g., "semantic_search", "group_by_comparison", "compare_step"
    params: Dict[str, Any] = field(default_factory=dict)
    next: List[str] = field(default_factory=list)
    branches: Dict[str, str] = field(default_factory=dict)
    fallback: Optional[str] = None
    description: str = ""

    def __post_init__(self):
        """Validate node type."""
        if self.type not in GRAPH_NODE_TYPES:
            valid = ", ".join(GRAPH_NODE_TYPES_LIST)
            raise ValueError(f"Unknown node type '{self.type}'. Valid types: {valid}")

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "type": self.type,
            "action": self.action,
            "params": {k: str(v)[:80] if not isinstance(v, (int, float, bool)) else v
                       for k, v in self.params.items()},
            "next": self.next,
            "branches": self.branches,
            "fallback": self.fallback,
            "description": self.description[:120] if self.description else "",
        }


@dataclass
class ExecutionGraph:
    """
    A directed graph of workflow nodes — the output of StrategyPlanner v2.

    THIS replaces ExecutionPlan. Instead of a flat list of independent
    directives, ExecutionGraph defines a true multi-step workflow with:

        • Sequential Chains:    retrieve → organize → reason
        • Conditional Branching:  Is evidence sufficient? → Yes/No
        • Multi-hop Retrieval:   retrieve → decide → retrieve_again → merge
        • Verification Loops:    reason → verify → (pass→end | fail→retry)
        • Parallel Streams:      retrieve_A ──→ merge ──→ reason
                                  retrieve_B ──→

    Architecture:
        StrategyPlanner (v2) → ExecutionGraph → GraphExecutor → Answer

    The GraphExecutor walks the graph topologically, dispatching each node
    to the appropriate module based on node.type.

    IMPORTANT: Downstream modules (EvidenceOrganizer, TaskSolver) consume
    ExecutionDirective objects extracted from node params via get_instruction().

    Attributes:
        task: The classified task type
        task_analysis: The full rich semantic description from TaskAnalyzer
        nodes: Dict of {node_id: GraphNode} — the actual graph structure
        entry_points: Ordered list of entry node IDs (graph can have multiple starts)
        task_specific_hints: Additional natural language instructions
    """
    task: TaskType = TaskType.GENERAL
    task_analysis: Optional[TaskAnalysis] = None
    nodes: Dict[str, GraphNode] = field(default_factory=dict)
    entry_points: List[str] = field(default_factory=list)
    task_specific_hints: str = ""

    # ──────────────────────────────────────────────
    # Graph topology helpers
    # ──────────────────────────────────────────────

    def get_node(self, node_id: str) -> Optional[GraphNode]:
        """Get a node by ID."""
        return self.nodes.get(node_id)

    def get_nodes_by_type(self, node_type: str) -> List[GraphNode]:
        """Get all nodes of a given type."""
        return [n for n in self.nodes.values() if n.type == node_type]

    def get_entry_nodes(self) -> List[GraphNode]:
        """Get the entry point node(s) of the graph."""
        return [self.nodes[eid] for eid in self.entry_points if eid in self.nodes]

    def get_successors(self, node: GraphNode) -> List[GraphNode]:
        """Get successor nodes (sequential next)."""
        return [self.nodes[nid] for nid in node.next if nid in self.nodes]

    def get_first_node_of_type(self, node_type: str) -> Optional[GraphNode]:
        """Get the first node of a given type (in topological order)."""
        ordered = self.topological_sort()
        for n in ordered:
            if n.type == node_type:
                return n
        return None

    def get_instruction(self, module: str) -> Optional["ExecutionDirective"]:
        """
        Get an ExecutionDirective for a specific downstream module.

        This is the bridge between ExecutionGraph and downstream components.
        Each module type corresponds to a node type:
            - "organization" → first "organize" node
            - "reasoning"    → first "reason" node
            - "retrieval"    → first "retrieve" node

        Args:
            module: Module name ("organization", "reasoning", "retrieval")

        Returns:
            ExecutionDirective with action + params, or None if not found
        """
        node_type_map = {
            "organization": "organize",
            "reasoning": "reason",
            "retrieval": "retrieve",
        }
        ntype = node_type_map.get(module)
        if not ntype:
            return None

        node = self.get_first_node_of_type(ntype)
        if not node:
            return None

        return ExecutionDirective(
            module=module,
            action=node.action,
            params=node.params,
        )

    def topological_sort(self) -> List[GraphNode]:
        """
        Return nodes in topological order (BFS from entry points).
        This determines the execution order.
        """
        visited: set = set()
        ordered: List[GraphNode] = []

        def bfs(start_ids: List[str]) -> None:
            queue = list(start_ids)
            while queue:
                nid = queue.pop(0)
                if nid in visited:
                    continue
                visited.add(nid)
                node = self.nodes.get(nid)
                if node:
                    ordered.append(node)
                    # Add next nodes
                    for next_id in node.next:
                        if next_id not in visited:
                            queue.append(next_id)
                    # Add branch targets
                    for branch_id in node.branches.values():
                        if branch_id not in visited and branch_id in self.nodes:
                            queue.append(branch_id)
                    # Add fallback
                    if node.fallback and node.fallback not in visited:
                        queue.append(node.fallback)

        bfs(self.entry_points)
        return ordered

    def contains_type(self, node_type: str) -> bool:
        """Check if the graph contains any node of the given type."""
        return any(n.type == node_type for n in self.nodes.values())

    def to_dict(self) -> Dict[str, Any]:
        return {
            "task": self.task.value if self.task else "unknown",
            "num_nodes": len(self.nodes),
            "entry_points": self.entry_points,
            "node_types": list(set(n.type for n in self.nodes.values())),
            "node_summary": {
                nid: n.type for nid, n in self.nodes.items()
            },
            "has_conditional_branching": any(
                len(n.branches) > 0 for n in self.nodes.values()
            ),
            "has_multi_hop_retrieval": len(self.get_nodes_by_type("retrieve")) > 1,
            "has_verification": self.contains_type("verify"),
            "task_specific_hints": self.task_specific_hints[:200] if self.task_specific_hints else "",
        }

    def visualize(self) -> str:
        """
        Simple ASCII visualization of the graph.
        """
        lines = [f"ExecutionGraph: {self.task.value if self.task else '?'}"]
        lines.append(f"  Nodes: {len(self.nodes)}, Entry: {self.entry_points}")
        lines.append("")

        ordered = self.topological_sort()
        for node in ordered:
            indent = "  "

            # Node header
            branches_str = ""
            if node.branches:
                branches_str = f" ──branch──> {list(node.branches.values())}"
            next_str = ""
            if node.next:
                next_str = f" ──> {node.next}"
            fallback_str = ""
            if node.fallback:
                fallback_str = f" [fallback: {node.fallback}]"

            dash = "●" if node.id in self.entry_points else "○"
            lines.append(f"{indent}{dash} [{node.type}] {node.id}: {node.action}{next_str}{branches_str}{fallback_str}")

            if node.params:
                for k, v in list(node.params.items())[:5]:
                    lines.append(f"{indent}  {k}: {v}")

        return "\n".join(lines)


# ============================================================
# Organized Evidence (Output of EvidenceOrganizer) - ENHANCED
# ============================================================

@dataclass
class OrganizedEvidence:
    """
    Cleaned, deduplicated, ranked, and task-aware grouped evidence.

    Enhanced: Now supports task-specific grouping strategies.
    The groups can be organized by compared-objects, symptoms,
    candidates, formulas, or chronological order depending on the task.

    Attributes:
        documents: Ranked list of evidence documents
        groups: Evidence grouped by task-specific strategy
        merged_ids: IDs of chunks that were merged
        preserved_citations: List of citation IDs that were preserved
        original_count: Number of documents before organization
        organized_count: Number of documents after organization
        organization_method: How the evidence was organized
    """
    documents: List[Any] = field(default_factory=list)
    groups: Dict[str, List[Any]] = field(default_factory=dict)
    merged_ids: List[str] = field(default_factory=list)
    preserved_citations: List[str] = field(default_factory=list)
    original_count: int = 0
    organized_count: int = 0
    organization_method: str = "topic"

    def to_dict(self) -> Dict[str, Any]:
        return {
            "original_count": self.original_count,
            "organized_count": self.organized_count,
            "num_groups": len(self.groups),
            "group_names": list(self.groups.keys()),
            "merged_chunks": len(self.merged_ids),
            "citations_preserved": len(self.preserved_citations),
            "organization_method": self.organization_method,
        }

    def get_all_documents(self) -> List[Any]:
        """
        Get ALL original documents regardless of group pruning.

        IMPORTANT (Recall-Safe Fix):
            Groups may be pruned by `_select_top_groups` (e.g. keep only 2-3
            groups). If we only read documents from `groups`, any chunk in a
            pruned group would be silently dropped from the final prompt —
            even though the Retriever had hit it and `self.documents` still
            holds it. Always read from the FULL `self.documents` list so that
            Grouping is only a *view*, never a *lossy filter*.
        """
        return list(self.documents)

    def get_context(self, separator: str = "\n---\n") -> str:
        """
        Build context string for LLM prompt preserving the full original chunks.

        Recall-Safe Design:
            - EVERY deduplicated original chunk in `self.documents` is emitted
              verbatim (no summary, no compression).
            - Group names (if any) are emitted as light headers INLINE, purely
              as a readability aid — they DO NOT drop any document.
            - Covers groups pruning: documents that fall into pruned groups
              are still emitted under a trailing "other evidence" header.
        """
        parts = []

        if self.groups:
            # Grouping is a VIEW, never a lossy filter: we still iterate over
            # EVERY document in self.documents (deduplicated originals), so
            # chunks whose group was pruned are NOT lost — they fall through to
            # the "other evidence" header. Group names are emitted INLINE purely
            # as a readability aid and never drop any original chunk.
            doc_to_group: Dict[int, str] = {}
            for group_name, docs in self.groups.items():
                for doc in docs:
                    doc_to_group[id(doc)] = group_name

            for doc in self.documents:
                rank = getattr(doc, "rank", 0)
                score = getattr(doc, "score", 0.0)
                content = getattr(doc, "content", "")
                citation = getattr(doc, "citation", f"[{rank}]")
                group_name = doc_to_group.get(id(doc))
                header = f"## [{group_name}]" if group_name else "## [other evidence]"
                parts.append(
                    f"\n{header}\n"
                    f"{citation} (score={score:.3f})\n{content}"
                )
        else:
            # No grouping — flat full list of every original chunk.
            for doc in self.documents:
                rank = getattr(doc, "rank", 0)
                score = getattr(doc, "score", 0.0)
                industry = getattr(doc, "industry", "")
                capability = getattr(doc, "capability", "")
                content = getattr(doc, "content", "")
                citation = getattr(doc, "citation", f"[{rank}]")
                parts.append(
                    f"{citation} (score={score:.3f}) [{industry}/{capability}]\n{content}"
                )

        context = separator.join(parts) if parts else ""
        return context





# ============================================================
# ExecutionDirective — used by organizer and solver modules
# ============================================================

@dataclass
class ExecutionDirective:
    """
    A directive from the execution plan instructing a module HOW to execute.

    Organizer and Solver both consume ExecutionDirective objects.
    These are typically extracted from ExecutionGraph node params.

    Attributes:
        module: Which module this directive targets ("organization", "reasoning", "retrieval")
        action: The specific action to execute
        params: Parameters for the action
    """
    module: str = ""
    action: str = ""
    params: Dict[str, Any] = field(default_factory=dict)

    @classmethod
    def from_params(cls, action: str = "", params: Optional[Dict[str, Any]] = None,
                    module: str = "") -> "ExecutionDirective":
        """Create directive from action + params (convenience constructor)."""
        return cls(module=module, action=action, params=params or {})


# ============================================================
# Deprecated Types (kept for backward compatibility)
# ============================================================

# Old config types are now merged into ExecutionPlan via directives.
# They remain importable for backward compatibility but are no longer
# the primary way modules consume the plan.

@dataclass
class AdaptiveRetrievalConfig:
    """
    DEPRECATED: Use ExecutionPlan directives instead.
    Kept for backward compatibility with ablation studies.
    """
    retrieve_k: int = 10
    use_multi_query: bool = False
    use_ked: bool = True
    use_fusion: bool = False
    min_score: Optional[float] = None
    source_priority: str = "standard"
    maximum_evidence: int = 20
    strategy_name: str = "standard"

    def to_dict(self) -> Dict[str, Any]:
        return {
            "retrieve_k": self.retrieve_k,
            "use_multi_query": self.use_multi_query,
            "use_ked": self.use_ked,
            "use_fusion": self.use_fusion,
            "min_score": self.min_score,
            "source_priority": self.source_priority,
            "maximum_evidence": self.maximum_evidence,
            "strategy_name": self.strategy_name,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "AdaptiveRetrievalConfig":
        return cls(
            retrieve_k=int(data.get("retrieve_k", 10)),
            use_multi_query=bool(data.get("use_multi_query", False)),
            use_ked=bool(data.get("use_ked", True)),
            use_fusion=bool(data.get("use_fusion", False)),
            min_score=float(data["min_score"]) if data.get("min_score") is not None else None,
            source_priority=str(data.get("source_priority", "standard")),
            maximum_evidence=int(data.get("maximum_evidence", 20)),
            strategy_name=str(data.get("strategy_name", "standard")),
        )


@dataclass
class AdaptiveOrganizationConfig:
    """
    DEPRECATED: Use ExecutionPlan directives instead.
    Kept for backward compatibility with ablation studies.
    """
    organize_by: str = "topic"
    remove_duplicate: bool = True
    group_key: str = "industry"
    prioritize_key: str = "general"
    enable_compression: bool = False

    def to_dict(self) -> Dict[str, Any]:
        return {
            "organize_by": self.organize_by,
            "remove_duplicate": self.remove_duplicate,
            "group_key": self.group_key,
            "prioritize_key": self.prioritize_key,
            "enable_compression": self.enable_compression,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "AdaptiveOrganizationConfig":
        return cls(
            organize_by=str(data.get("organize_by", "topic")),
            remove_duplicate=bool(data.get("remove_duplicate", True)),
            group_key=str(data.get("group_key", "industry")),
            prioritize_key=str(data.get("prioritize_key", "general")),
            enable_compression=bool(data.get("enable_compression", False)),
        )


@dataclass
class AdaptiveReasoningFlow:
    """
    DEPRECATED: Use ExecutionPlan directives instead.
    Kept for backward compatibility with ablation studies.
    """
    reasoning_type: str = "general"
    workflow_steps: List[str] = field(default_factory=list)
    prompt_style: str = "standard"
    requires_verification: bool = False
    requires_citation: bool = True

    def to_dict(self) -> Dict[str, Any]:
        return {
            "reasoning_type": self.reasoning_type,
            "workflow_steps": self.workflow_steps,
            "prompt_style": self.prompt_style,
            "requires_verification": self.requires_verification,
            "requires_citation": self.requires_citation,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "AdaptiveReasoningFlow":
        return cls(
            reasoning_type=str(data.get("reasoning_type", "general")),
            workflow_steps=list(data.get("workflow_steps", [])),
            prompt_style=str(data.get("prompt_style", "standard")),
            requires_verification=bool(data.get("requires_verification", False)),
            requires_citation=bool(data.get("requires_citation", True)),
        )


@dataclass
class StrategyPlan:
    """
    DEPRECATED: Use ExecutionPlan instead.
    Kept for backward compatibility with existing tests.
    """
    task: TaskType = TaskType.GENERAL
    task_analysis: Optional[TaskAnalysis] = None
    retrieval_config: AdaptiveRetrievalConfig = field(default_factory=AdaptiveRetrievalConfig)
    organization_config: AdaptiveOrganizationConfig = field(default_factory=AdaptiveOrganizationConfig)
    reasoning_flow: AdaptiveReasoningFlow = field(default_factory=AdaptiveReasoningFlow)
    prompt_template_key: str = "general"
    task_specific_hints: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            "task": self.task.value,
            "retrieval_config": self.retrieval_config.to_dict(),
            "organization_config": self.organization_config.to_dict(),
            "reasoning_flow": self.reasoning_flow.to_dict(),
            "prompt_template_key": self.prompt_template_key,
            "task_specific_hints": self.task_specific_hints[:200] if self.task_specific_hints else "",
        }
